<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.SqlServer" />
    <PackageReference Include="MailKit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FitnessClub.Application\FitnessClub.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Notifications\Templates\*.html" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="FitnessClub.ArchitectureTests" />
    <InternalsVisibleTo Include="FitnessClub.IntegrationTests" />
  </ItemGroup>
</Project>
